sylius_grid:
    grids:
        setono_sylius_terms_terms:
            driver:
                name: doctrine/orm
                options:
                    class: "%setono_sylius_terms.model.terms.class%"
            fields:
                code:
                    type: string
                    label: setono_sylius_terms.ui.code
                name:
                    type: string
                    label: setono_sylius_terms.ui.name
                channel:
                    type: string
                    label: setono_sylius_terms.ui.channel
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
